# Generated by Django 5.2.16 on 2026-07-31 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadanos', '0003_direccion_requisito_solicitud_archivorequisito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('folio_cita', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada'), ('Reprogramada', 'Reprogramada')], default='Programada', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Notas o instrucciones para el ciudadano', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_ciudadano', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_funcionario', to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='ciudadanos.tramite')),
            ],
            options={
                'db_table': 'principal_cita',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
