# Generated by Django 5.2.16 on 2026-07-31 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadanos', '0004_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(help_text='Hora a la que abren la ventanilla')),
                ('hora_fin', models.TimeField(help_text='Hora a la que cierran la ventanilla')),
                ('duracion_cita_minutos', models.IntegerField(default=30, help_text='¿Cuánto dura cada cita en minutos?')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='ciudadanos.direccion')),
            ],
            options={
                'db_table': 'principal_horario_direccion',
                'unique_together': {('direccion', 'dia_semana')},
            },
        ),
    ]
